### ISSUE TITLE
Noob Problem Probably

### ISSUE THREAD

**Issue by EdV2** [AllenInstitute/pytic#3]
Hi,
   when execute the code provided by Pololu 
https://www.pololu.com/blog/788/pytic-python-interface-for-pololu-tic-stepper-motor-controllers

I get the following error during the "# Connect to first available Tic Device serial number over USB"

  File "C:\Anaconda3\lib\site-packages\pytic\pytic.py", line 113, in _tic_handle_open
    print(handle_p);

ValueError: NULL pointer access

Please advise.

Thanks!

**Comment by ajbenz18** [comment]
I'm getting this error as well. Did you figure out why this was happening and how to fix it?

**Comment by ajbenz18** [comment]
I managed to solve the issue by disconnecting the tic control center from the motor

**Comment by Em607867** [comment]
> I managed to solve the issue by disconnecting the tic control center from the motor

Were you able to load the yml file for the settings? I get an error message while trying to do that, any insights will be helpful.

Thanks!

**Comment by bensmana** [comment]
Unfortunately I no longer work for the company on who's behalf I was working with the motors, but I still have access to the code. It's been a while, so I don't really remember anything about the issue, so I can really only share with you the how I used the motor.

```tic = pytic.PyTic()
            # Connect to first available Tic Device serial number over USB
            serial_nums = tic.list_connected_device_serial_numbers()
            print(serial_nums)
            tic.connect_to_serial_number(serial_nums[0])
            tic.settings.load_config('tic_config.yaml')
            tic.settings.apply()  
```

tic_config.yaml:
```
tic_settings:
  product: TIC_PRODUCT_T825
  never_sleep: True
  auto_clear_driver_error: True
  ignore_err_line_high: True
  serial_crc_enabled: False
  command_timeout: 0
  target_velocity: 40000000
  max_speed: 40000000                 # pulses/s * 10^-4
  starting_speed: 0                   # pulses/s * 10^-4
  max_accel: 900000                  # pulses/s^2 * 10^-2
  max_decel: 900000                  # pulses/s^2 * 10^-2
  step_mode: TIC_STEP_MODE_MICROSTEP2 
  current_limit: 672 # mA (see table in Pololu manual for acceptable values)
  decay_mode: TIC_DECAY_MODE_T825_FAST 
  pin_settings:
    - pin_num: TIC_PIN_NUM_RX
      func: TIC_PIN_FUNC_USER_INPUT
      pullup: True
      analog: False
```

Perhaps share the error message you're getting, and I'll see if I can be of any more help.
